### ISSUE TITLE
Can you document how to use this?

### ISSUE THREAD

**Issue by matthew-dean** [poseidon/wait-for-status-checks#194]
The [Usage](https://github.com/poseidon/wait-for-status-checks?tab=readme-ov-file#usage) section says this:

> success - All check runs completed as either success or skipped
> failure - One or more check runs completed as with a non-successful conclusion (e.g. failure, stale, timed_out, cancelled)

However, for noobs, can you just put an example in the README that actually illustrates where / how to check `success` or `failure`?

**Comment by dghubble** [comment]
The [usage section](https://github.com/poseidon/wait-for-status-checks?tab=readme-ov-file#usage) shows the GitHub Workflow you would add to your own repo.

```yaml
name: summary
on:
  pull_request:
jobs:
  enforce-all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

Any Pull Requests will have this extra workflow (`summary / enforce-all-checks``), whose purpose is to watch the other check runs on the same PR and wait for them to complete. If all the watched jobs succeed, the workflow succees. Else it fails. This is useful because you can make `summary / enforce-all-checks` a required check. Your repo might use dozens or hundreds of difference checks, some conditional. But you only have to have this one be required. 

The README links to a lot of relevant context. And this repo itself uses a `summary / enforce-all-checks` workflow if you look at PRs.

> Say this action is not triggered by a pull request

You wouldn't. That would not make sense to do
