### ISSUE TITLE
Action does not self-ignore if the job has a name

### ISSUE THREAD

**Issue by joergbonprix** [poseidon/wait-for-status-checks#303]
I noticed that if the job is given a name, then the action does not exclude its own check run and waits until it times out or is canceled:

```yaml
jobs:
  enforce-all-checks:
    name: "Some name" # this causes the job to wait for itself
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

Looking at the code, I'm not sure if this can be fixed – it might be a limitation of GitHub providing the running job with its ID but only reporting the name for check runs. I've not investigated further, as this is trivial to work around by simply not setting a name.
