### ISSUE TITLE
Ignore previously failed checks on pull_request edited

### ISSUE THREAD

**Issue by perryao** [poseidon/wait-for-status-checks#383]
We have a workflow that checks the format of a PR title and it runs on 

```
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
```

If I open a PR with a title that fails this check, our summary workflow below fails as expected:

```
name: Summary
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  require-all-checks:
    name: Require All Checks
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Wait for Status Checks
        uses: poseidon/wait-for-status-checks@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: Require All Checks
          ignore_pattern: '\[Optional\].*'
```

However, if I edit the PR title and get the PR title workflow to run again and pass, the require-all-checks workflow still fails.

Is there a way to ignore previous failures on pull request edited triggers?
