### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by tekumara** [poseidon/wait-for-status-checks#63]
```
##[error]error HttpError: Resource not accessible by integration
```

**Comment by tekumara** [comment]
I was missing permissions on the job:
```yaml
jobs:
  enforce-all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
```
